### ISSUE TITLE
Search field on mobile device without function

### ISSUE THREAD

**Issue by Markoise** [nextcloud/tables#1079]
### Steps to reproduce

1. open tables on a mobile phone
2. open a table
3. try to type something in the search field

### Expected behavior

on-screen keyboard appears on mobile view of website

### Actual behavior

If you open the Tables app on a mobile device and click in the search field, no on-screen keyboard appears. 
If you switch the browser to "Desktop website", it works.
This occurs since update to tables 0.7.1

### Tables app version

0.7.2

### Browser

Brave, Chrome (mobile view)

### Client operating system

Android 14

### Operating system

Debian

### Web server

Nginx

### PHP engine version

PHP 8.2

### Database

MariaDB

**Comment by Markoise** [comment]
Am I the only one who has this annoying problem?

**Comment by Markoise** [comment]
Same Problem with 0.7.4 on every browser.

**Comment by blizzz** [comment]
Also reproducible in browser, when the windows is small, or the zoom is huge. Essentially, when the width is 510px at most. 

Talk has the same problem, so the underlying issue seems to be within the nextcloud-vue component. If I understand correctly, this issue is related: https://github.com/nextcloud-libraries/nextcloud-vue/issues/5385 

 @Antreesy am i right?

**Comment by Antreesy** [comment]
I'm pretty sure it is the same issue. Will try to take a look on it today or involve other maintainers

**Comment by Markoise** [comment]
Unfortunately, the problem still exists with version 0.7.5. Unfortunately, this makes the app unusable for our purposes since May. 😢

**Comment by Markoise** [comment]
Since 0.8.0 it works.
Thanks you so much. 🤗
