### ISSUE TITLE
Formatted text editor bar is rendered above selection list

### ISSUE THREAD

**Issue by pktiuk** [nextcloud/tables#292]
### Steps to reproduce

1. Create table with: multiple selection column (add 3-4 options to this one)
2. Add Rich text column
3. Try to create new row

### Expected behavior

I whould be able to all of the elements in list

### Actual behavior

When I try to select something:  

![image](https://github.com/nextcloud/tables/assets/45544416/e5e6e955-582e-4d6a-bd2c-3b15fb2af386)

Before opening list selector:

![image](https://github.com/nextcloud/tables/assets/45544416/1d1f53e8-1083-434e-8a2f-04e24edc93de)

### Tables app version

0.5

### Browser

Firefox and Chrome

### Client operating system

Linux

### Web server

None

### PHP engine version

None

### Database

None

**Comment by juliushaertl** [comment]
Related https://github.com/nextcloud/deck/pull/4617

Maybe we should even fix this in text

**Comment by Hephi2** [comment]
Yes, the issue can be fixed by setting reducing the z-index of the text-menubar, e.g., to value 1.
https://github.com/nextcloud/text/blob/c3f9086c0beaf50fdf44ccea5daf02bc48e75d01/src/components/Menu/MenuBar.vue#LL283C4-L283C4

I'm not sure why it has this value right now

Btw. this problem is with every dropdown menu, also, e.g., with the date picker
